"""
AI Command Schemas
Pydantic schema definitions for structured remote control commands generated by AI / NLP engines.
"""

from typing import Optional, List, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field


class IntentEnum(str, Enum):
    POWER = "POWER"
    VOLUME = "VOLUME"
    MUTE = "MUTE"
    CHANNEL = "CHANNEL"
    INPUT = "INPUT"
    NAVIGATION = "NAVIGATION"
    APPLICATION = "APPLICATION"
    PLAYBACK = "PLAYBACK"
    MENU = "MENU"
    GUIDE = "GUIDE"
    FAVORITES = "FAVORITES"
    DEVICE_SWITCH = "DEVICE_SWITCH"
    DEVICE_DISCOVERY = "DEVICE_DISCOVERY"
    SCENE = "SCENE"
    STATUS = "STATUS"


class ActionEnum(str, Enum):
    ON = "on"
    OFF = "off"
    TOGGLE = "toggle"
    SET = "set"
    UP = "up"
    DOWN = "down"
    MUTE = "mute"
    UNMUTE = "unmute"
    OPEN = "open"
    CLOSE = "close"
    CHANGE = "change"
    SWITCH = "switch"
    DISCOVER = "discover"
    EXECUTE = "execute"
    QUERY = "query"
    NAVIGATE = "navigate"
    PLAY = "play"
    PAUSE = "pause"
    STOP = "stop"
    FORWARD = "forward"
    REWIND = "rewind"


class AICommand(BaseModel):
    """Normalized structured command for device execution."""
    device_id: Optional[str] = Field(default=None, description="Target device ID or None for active device")
    intent: IntentEnum = Field(description="High-level command intent")
    action: ActionEnum = Field(description="Specific action verb")
    value: Optional[Any] = Field(default=None, description="Numeric or string value (e.g. volume level, delta)")
    channel: Optional[str] = Field(default=None, description="Channel number or channel name")
    application: Optional[str] = Field(default=None, description="App name (e.g. YouTube, Netflix)")
    input_source: Optional[str] = Field(default=None, description="HDMI 1, HDMI 2, AV, etc.")
    direction: Optional[str] = Field(default=None, description="UP, DOWN, LEFT, RIGHT, OK, BACK, HOME")
    scene_name: Optional[str] = Field(default=None, description="Scene name for SCENE intent")
    requires_confirmation: bool = Field(default=False, description="Flag for risky operations (power off all, factory reset)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    explanation: Optional[str] = Field(default=None, description="Natural language explanation of what will be done")


class CommandSequence(BaseModel):
    """Ordered sequence of AI commands to execute sequentially."""
    commands: List[AICommand]
    original_prompt: str
    is_multi_step: bool = False


class CommandValidationResult(BaseModel):
    """Result of command schema and capability validation."""
    is_valid: bool
    command: Optional[AICommand] = None
    rejection_reason: Optional[str] = None
    suggested_fix: Optional[str] = None
